### ISSUE TITLE
reply_markup

### ISSUE THREAD

**Issue by fopina** [datamachine/twx#4]
How do I use reply_markup in send_message?

I've tried

```
bot.send_message(message.chat.id, 'done', reply_to_message_id=message.message_id, reply_markup=ReplyKeyboardHide(hide_keyboard=True, selective=False))
```

In this class https://github.com/fopina/py-tgbot/blob/master/tgbot/types.py (that I'll discontinue now that I found your library that looks more advanced and robust :)) I managed to use reply_markup but only if the required parameter is the only sent (force_reply or hide_keyboard or keyboard). If any other optional parameter is passed (like selective or one_time_keyboard) then the whole reply_markup instruction is ignored..
I was hoping I could see what I was doing wrong in the JSON-serialization looking at yours, but I can't get it to work in yours...

Thanks

**Comment by fopina** [comment]
After enabling logging I see that I'm probably using it wrong indeed...

```
Content-Type: application/x-www-form-urlencoded

text=done&reply_to_message_id=615&reply_markup=True&reply_markup=False&chat_id=...
```

reply_markup should be the JSON serialized object such as

```
reply_markup=%7B%22hide_keyboard%22%3Atrue%7D
```

**Comment by xlopo** [comment]
ReplyKeyboardMarkup is now implemented and documented. A usage example can be found in the docstring here https://github.com/datamachine/twx/blob/master/twx/botapi/botapi.py#L313-L350

I will push the update to pypi after I finish testing

**Comment by fopina** [comment]
Perfect, nice and easy to use.

But, if I call it like this:
```
tg.send_message(message.chat.id, reply, reply_to_message_id=message.message_id, reply_markup=ReplyKeyboardMarkup.create(keyboard=[['asd']]))
```
it works nicely. If I add one of the options such as:
```
tg.send_message(message.chat.id, reply, reply_to_message_id=message.message_id, reply_markup=ReplyKeyboardMarkup.create(keyboard=[['asd']], one_time_keyboard=True))
```
It serializes to
```
reply_markup=%7B%22one_time_keyboard%22%3A+true%2C+%22keyboard%22%3A+%5B%5B%22asd%22%5D%5D%7D
```
which is exactly what I was doing in my library and the result is the same as with my library: it doesn't work, the keyboard options do not even show up (the whole markup is ignored)
